// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqiqddwxrgtvrifwdsjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxaXFkZHd4cmd0dnJpZndkc2p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5Njc1NDMsImV4cCI6MjA2OTU0MzU0M30.0TYzgq1ItgI6k8khtfXBmkNXHPl_NV0rNY7SHT_8Z2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});